name: flutter_appbar
description: "This package implements the flexible appbar behavior, And we pursue higher performance and responsiveness than the appbar generally provided by Flutter."
version: 1.7.0
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/flutter_appbar
keywords:
  - flutter
  - flutter ui
  - appbar
  - scroll
  - nested scroll
  - sliver free
  - flexible appbar
  - floating appbar
  - expandable appbar
  - premium
  - responsive
  - high performance
  - smooth scrolling
  - optimized
  - easy to use
  - simple
  - effortless

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
